apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-hello-fun
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-hello-fun
spec:
  source:
    git:
      url: https://github.com/sanjimoh/tap-hello-fun.git
      ref:
        branch: main
